check_task:
  container:
    image: elixir:1.9.2-alpine
  hex_script: mix local.hex --force
  rebar_script: mix local.rebar --force
  mix_deps_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script: mix deps.get
  build_cache:
    folder: _build
  check_script: mix check